dependencies:
- name: zeebe-cluster
  repository: https://helm.zeebe.io
  version: 0.0.122
- name: zeebe-operate
  repository: https://helm.zeebe.io
  version: 0.0.22
  condition: "zeebe-operate.enabled"
- name: elasticsearch
  repository: http://helm.elastic.co 
  version: 7.7.0
  condition: "elasticsearch.enabled"
- name: kibana
  repository: http://helm.elastic.co 
  version: 7.7.0
  condition: "kibana.enabled"
- name: mysql
  version: 1.6.2
  repository: "https://kubernetes-charts.storage.googleapis.com"
  alias: operationsMysql
  condition: "operations.enabled"

