dependencies:
- name: zeebe-cluster
  repository: https://helm.camunda.io
  version: 0.0.122
- name: zeebe-operate
  repository: https://helm.camunda.io
  version: 0.0.28
  condition: "zeebe-operate.enabled"
- name: elasticsearch
  repository: http://helm.elastic.co 
  version: 7.11
  condition: "elasticsearch.enabled"
- name: kibana
  repository: http://helm.elastic.co 
  version: 7.11
  condition: "kibana.enabled"
- name: mysql
  version: 1.6.2
  repository: "https://charts.helm.sh/stable"
  alias: operationsMysql
  condition: "operations.enabled"

