global:
  zeebe: "ph-ee-zeebe"
  elasticsearch: # used by operate
    host: ph-ee-elasticsearch-master
    clusterName: elasticsearch

zeebe-cluster:
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]
  env:

  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
  kibana:
    enabled: false
  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "http://jenkins.mifos.io:8081/service/rest/v1/search/assets/download?maven.groupId=hu.dpc.phee&maven.artifactId=exporter&maven.baseVersion=1.0.0-SNAPSHOT&sort=latest"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

#  zeebeCfg: |
#    exporters:
#      - id: ph-ee-kafka-exporter
#        jarPath: /exporters/ph-ee-kafka-exporter.jar
#        className: hu.dpc.rt.kafkastreamer.exporter.KafkaExporter

# payment hub Operate, ES and Kibana
zeebe-operate:
  enabled: false
  fullnameOverride: "ph-ee-zeebe-operate"

elasticsearch:
  enabled: false
  imageTag: 6.8.5
  replicas: 1
  minimumMasterNodes: 1

kibana:
  enabled: false
  imageTag: 6.8.5
  fullnameOverride: "ph-ee-kibana"

operations:
  enabled: true

operationsMysql:
  fullnameOverride: operations-mysql

identityMysql:
  fullnameOverride: identity-mysql

ph_ee_connector_ams_mifos:
  SPRING_PROFILES_ACTIVE: ""

ph_ee_connector_mojaloop:
  SPRING_PROFILES_ACTIVE: ""

ph_ee_connector_channel:
  SPRING_PROFILES_ACTIVE: ""
  hostname: ""

ph_ee_identity_provider:
  SPRING_PROFILES_ACTIVE: ""
  hostname: ""

ph_ee_operations:
  hostname: ""
  webhost: ""
