global:
  zeebe: "ph-ee-zeebe"
  elasticsearch: # used by operate
    host: ph-ee-elasticsearch-master
    clusterName: elasticsearch

zeebe-cluster:
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]
  
  # zeebe's ES and Kibana
  elasticsearch:
    enabled: false
  kibana:
    enabled: false
  
# payment hub Operate, ES and Kibana
zeebe-operate:
  enabled: false
  fullnameOverride: "ph-ee-zeebe-operate"

elasticsearch:
  enabled: false
  imageTag: 6.8.5
  replicas: 1
  minimumMasterNodes: 1
  
kibana:
  enabled: false
  imageTag: 6.8.5
  fullnameOverride: "ph-ee-kibana"
  
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
  
