zeebe-cluster:
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]
  
  elasticsearch:
    enabled: false
    imageTag: 6.8.5
    replicas: 1
    minimumMasterNodes: 1
  
  kibana:
    enabled: false
    imageTag: 6.8.5
  
  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
  
