kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"
  elasticsearch:
    url: "https://ph-ee-elasticsearch:9200/"
    bulk-size: 20
    index-prefix: "zeebe-record"


elasticsearch:
  security:
    enabled: false
  sslVerification: false
  username: "elastic"
  password: "somepassword"

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%35.35t]){faint} %clr(%-28.28logger{28}){cyan} %clr(:){faint}%X{BUSINESS-LOG} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"


reporting:
  enabled: true
