kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"
  elasticsearch:
    url: "http://ph-ee-elasticsearch:9200/"
    bulk-size: 20
    index-prefix: "zeebe-record"

logging:
  level:
    ROOT: ERROR
