camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-{dfspid}"
    transaction-request: "PayeeTransactionRequest-{dfspid}"
    party-registration: "PartyRegistration-{dfspid}"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "ph-ee-zeebe:26500"

rest:
  authorization:
    enabled: false
    host: http://localhost:8080

operations:
  url: "http://med-operations.mifos.io/oauth/token"

identity:
  url: "http://med-identity.mifos.io/oauth/token"
  channel:
    clients:
      - clientId: channel-tn06
        clientSecret: p1234
        tenant: tn06