camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-DFSPID"

zeebe:
  broker:
    contactpoint: "ph-ee-zeebe:26500"
