camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-{tenant}"
    transaction-request: "PayeeTransactionRequest-{tenant}"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "ph-ee-zeebe:26500"

rest:
  authorization:
    enabled: false
    host: http://localhost:8080
