operations:
  url: "http://med-operations.mifos.io/api/v1"

identity:
  url: "http://med-identity.mifos.io/oauth/token"
  channel:
    clients:
      - clientId: channel-tn05
        clientSecret: p2345
        tenant: tn05
      - clientId: channel-tn06
        clientSecret: p2345
        tenant: tn06