zeebe:
  broker:
    exporters:
      kafkastreamer:
        className: hu.dpc.rt.kafkastreamer.exporter.KafkaExporter
        jarPath: /usr/local/zeebe/lib/exporter-1.0.0-SNAPSHOT.jar
        args:
          url: http://kafka:9092/
          index:
            prefix: zeebe-record
            createTemplate: true
            command: false
            event: true
            rejection: false
            deployment: false
            error: true
            incident: true
            job: false
            jobBatch: false
            message: false
            messageSubscription: false
            variable: true
            variableDocument: false
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
            ignoreVariablesAbove: 32677

      # Configure exporters below
      #
      # Each exporter should be configured following this template:
      #
      # jarPath:
      #   path to the JAR file containing the exporter class. JARs are only loaded once, so you can define
      #   two exporters that point to the same JAR, with the same class or a different one, and use args
      #   to parametrize its instantiation.
      # className:
      #   entry point of the exporter, a class which *must* extend the io.zeebe.exporter.Exporter
      #   interface.
      #
      # A nested table as "args:" will allow you to inject arbitrary arguments into your
      # class through the use of annotations.
      #
      # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_[exporter name]_..."
      #

      # Debug Log Exporter --------------
      #
      # Enable the following debug exporter to log the exported records to console
      #
      # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_DEBUGLOG_..."
      #
      # debuglog:
        # className: io.zeebe.broker.exporter.debug.DebugLogExporter
        # args:
        #   logLevel: debug
        #   prettyPrint: false

      # Debug HTTP Export ---------------
      #
      # Enable the following debug exporter to start a http server to inspect the exported records
      #
      # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_DEBUGHTTP_..."
      #
      # debugHttp:
        # className: io.zeebe.broker.exporter.debug.DebugHttpExporter
        # args:
        #   port = 8000
        #   limit = 1024

      # Elasticsearch Exporter ----------
      # An example configuration for the elasticsearch exporter:
      #
      # These setting can also be overridden using the environment variables "ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_..."
      #
      elasticsearch:
        className: io.zeebe.exporter.ElasticsearchExporter
        #
        args:
          url: http://ph-ee-elasticsearch-master:9200
        #
          bulk:
            delay: 5
            size: 1000
        #
        #   authentication:
        #     username: elastic
        #     password: changeme
        #
          index:
            prefix: zeebe-record
            createTemplate: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: false
            messageSubscription: false
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
            ignoreVariablesAbove: 32677

