datasource:
  core:
    host: operationsmysql
    port: 3306
    schema: tenants
    username: mifos
    password: password
  common:
    protocol: "jdbc"
    subprotocol: mysql
    driverclass_name: com.mysql.cj.jdbc.Driver

transfer:
  flows:
    - name: PayerFundTransfer
      direction: OUTGOING
      transformers:
        - field: amount
          variableName: amount
          jsonPath: $.amount.amount
        - field: currency
          variableName: currency
          jsonPath: $.amount.currency
        - field: payeePartyIdType
          variableName: partyIdType
          jsonPath: $.payee.partyIdInfo.partyIdType
        - field: payeePartyId
          variableName: partyIdentifier
          jsonPath: $.payee.partyIdInfo.partyIdentifier
        - field: payerPartyIdType
          variableName: partyIdType
          jsonPath: $.payer.partyIdInfo.partyIdType
        - field: payerPartyId
          variableName: partyIdentifier
          jsonPath: $.payee.partyIdInfo.partyIdentifier
        - field: transactionId
          variableName: transactionId
        - field: currency
          variableName: currency
        - field: batchId
          variableName: batchId
        - field: tenantId
          variableName: tenantId

    - name: binx_hct_inst_credit_transfer_debtor_process
      direction: OUTGOING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAgent.FinancialInstitutionIdentification.BICFI
        - field: payeePartyId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].CreditorAccount.Identification.IBAN
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].DebtorAgent.FinancialInstitutionIdentification.BICFI
        - field: payerPartyId
          variable_name: debtorIban
        - field: payerPartyIdType
          constant: IBAN
        - field: payerFee
          variable_name: transactionFeeAmount
        - field: payerFeeCurrency
          variable_name: currency
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: direction
          constant: OUTGOING
        - field: clientCorrelationId
          variable_name: originalPain001
          json_path: $.Document.PaymentInformation[0].CreditTransferTransactionInformation[0].PaymentIdentification.EndToEndIdentification
    - name: binx_hct_inst_credit_transfer_creditor_process
      direction: INCOMING
      transformers:
        - field: transactionId
          variable_name: internalCorrelationId
        - field: payeeDfspId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/CdtrAgt/FinInstnId/BIC
        - field: payeePartyId
          variable_name: creditorIban
        - field: payeePartyIdType
          constant: IBAN
        - field: payerDfspId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAgt/FinInstnId/BIC
        - field: payerPartyId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAcct/Id/IBAN
        - field: payerPartyIdType
          constant: IBAN
        - field: amount
          variable_name: amount
        - field: currency
          variable_name: currency
        - field: clientCorrelationId
          variable_name: originalPacs008
          xpath: /SendCreditTransferRequest/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/EndToEndId