camel:
  server-port: 5000
  springboot:
    main-run-controller: true
    dataformat:
      json-jackson:
        auto-discover-object-mapper: true

application:
  bucket-name: paymenthub-ee-dev

kafka:
  bootstrapAddress: "kafka:9092"
  topic:
    gsma:
      name: gsma
    slcb:
      name: slcb

zeebe:
  client:
    max-execution-threads: 1000
    evenly-allocated-max-jobs: 1000
    #    max-execution-threads: 100
    #    number-of-workers: 8
    #    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "zeebe-zeebe-gateway:26500"

cloud:
  aws:
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAX32JM37TYOG3QUJU}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false
  azure:
    enabled: false
    blob:
      connection-string:


dfspids: "ibank-usa,ibank-india"

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-{dfspid}"
    transaction-request: "PayeeTransactionRequest-{dfspid}"
    party-registration: "PartyRegistration-{dfspid}"
    gsma-base-transaction: "gsma_base_transaction-{dfspid}"
    gsma-int-transfer: "gsma_int_transfer-{dfspid}"
    gsma-payee-process: "gsma_payee_process"
    gsma-bill-payment: "gsma_bill_payment"
    gsma-link-based-payment: "gsma_link_transfer"
    international-remittance-payee: "international_remittance_payee_process-{dfspid}"
    international-remittance-payer: "international_remittance_payer_process-{dfspid}"
    debit-party-process: "debit_party_process-{dfspid}"

operations-app-host: ""