
[[exporters]]
id = "kafkastreamer"
className = "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
[exporters.args]
url = "http://kafka:9092"
[exporters.args.bulk]
 delay = 5
 size = 1_000

 [exporters.args.index]
 prefix = "zeebe-record"
 createTemplate = true

 command = false
 event = true
 rejection = false

 deployment = true
 incident = true
 job = true
 message = false
 messageSubscription = false
 raft = false
 workflowInstance = true
 workflowInstanceSubscription = false

