apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-channel"
  labels:
    app: ph-ee-connector-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-channel
  template:
    metadata:
      labels:
        app: ph-ee-connector-channel
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-channel
          image: "{{ .Values.channel.image }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            limits:
              memory: "768M"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.channel.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-connector-channel
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Values.channel.hostname }}"
      http:
        paths:
        - path: /channel
          pathType: Prefix
          backend:
            service:
              name: ph-ee-connector-channel
              port: 
                number: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-channel
  name: ph-ee-connector-channel
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-channel
  sessionAffinity: None
  type: ClusterIP
