{{- if .Values.mpesa.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-mpesa"
  labels:
    app: ph-ee-connector-mpesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-mpesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-mpesa
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-mpesa
          image: "{{ .Values.mpesa.image }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            limits:
              memory: "512M"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.mpesa.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "MPESA_LOCAL_HOST"
              value: "https://mpesa.ibank.financial"
            - name: "MPESA_AUTH_CLIENT-KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mpesa.secret.name }}"
                  key: "{{ .Values.mpesa.secret.key.auth_client_key }}"
            - name: "MPESA_AUTH_CLIENT-SECRET"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mpesa.secret.name }}"
                  key: "{{ .Values.mpesa.secret.key.auth_client_secret }}"
            - name: "MPESA_API_PASS-KEY"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mpesa.secret.name }}"
                  key: "{{ .Values.mpesa.secret.key.api_pass_key }}"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mpesa
  name: ph-ee-connector-mpesa
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mpesa
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mpesa-secret
type: Opaque
data:
  client-key: cmVwbGFjZSB0aGlzIHdpdGggY2xpZW50IGtleQo=
  client-secret: cmVwbGFjZSB0aGlzIHdpdGggY2xpZW50IHNlY3JldAo=
  pass-key: cmVwbGFjZSB0aGlzIHdpdGggcGFzcyBrZXkK
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-connector-mpesa
  annotations:
{{- if .Values.mpesa.ingress.annotations }}
{{ toYaml .Values.mpesa.ingress.annotations | indent 4 }}
{{- end }}

spec:
  rules:
    - host: "{{ .Values.mpesa.hostname }}"
      http:
        paths:
          - path: /mpesa
            pathType: Prefix
            backend:
              service:
                name: ph-ee-connector-mpesa
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"

{{- end }}
