{{- if .Values.messagegateway.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "message-gateway"
  labels:
    app: message-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-gateway
  template:
    metadata:
      labels:
        app: message-gateway
    spec:
      containers:
        - name: message-gateway
          image: "{{ .Values.messagegateway.image }}"
          ports:
            - containerPort: 9191
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 30
          env:
            - name: spring.datasource.url
              value: jdbc:mysql:thin://operations-mysql:3306/messagegateway
            - name: spring.datasource.username
              value: "mifos"
            - name: spring.datasource.password
              value: "password"
            - name: "CALLBACKCONFIG_HOST"
              value: "{{ .Values.messagegateway.CALLBACKCONFIG_HOST }}"
            - name: "HOSTCONFIG_HOST"
              value: "{{ .Values.messagegateway.HOSTCONFIG_HOST }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-gateway
  name: message-gateway
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 9191
  selector:
    app: message-gateway
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-gateway
  annotations:
{{- if .Values.messagegateway.ingress.annotations }}
{{ toYaml .Values.messagegateway.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.messagegateway.hostname }}"
      http:
        paths:
          - path: /messages
            pathType: Prefix
            backend:
              service:
                name: message-gateway
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"

{{- end }}