apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-notifications"
  labels:
    app: ph-ee-connector-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-notifications
  template:
    metadata:
      labels:
        app: ph-ee-connector-notifications
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-notifications
          image: "{{ .Values.notifications.image }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          ports:
           - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.notifications.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "HOSTCONFIG_HOST"
              value: "message-gateway"
            - name: "HOSTCONFIG_PORT"
              value: "80"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-notifications
  name: ph-ee-connector-notifications
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-notifications
  sessionAffinity: None
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-notifications
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.messagegateway.ingress.class}}"
spec:
  rules:
    - host: "{{ .Values.notifications.hostname }}"
      http:
        paths:
          - path: /notifications
            pathType: Prefix
            backend:
              service:
                name: ph-ee-connector-notifications
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
