kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"

spring:
  jpa:
    show-sql: false
    properties:
      eclipselink:
        logging:
          logger: "hu.dpc.phee.operate.importer.config.EclipselinkLogger"
  datasource:
    url: "jdbc:mysql://operator-mysql:3306/operator?rewriteBatchedStatements=true"
    username: "mifos"
    password: "password"
