datasource:
  core:
    host: localhost
    port: 5432
    schema: operations
    username: postgres
    password: password
  common:
    protocol: "jdbc"
    subprotocol: postgresql
    driverclass_name: org.postgresql.Driver
