kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"
    reset: false

spring:
  jpa:
    show-sql: false
    properties:
      eclipselink:
        logging:
          logger: "hu.dpc.phee.operator.config.EclipselinkLogger"
    open-in-view: false

datasource:
  common:
    protocol: "jdbc"
    subprotocol: "mysql"
    driverclass_name: "com.mysql.cj.jdbc.Driver"
  core:
    port: 3306
    host: "operations-mysql"
    schema: "tenants"
    username: "mifos"
    password: "password"

server:
  port: 8000

bpmn:
  transfer-type: "TRANSFER"
  transaction-request-type: "TRANSACTION-REQUEST"
  incoming-direction: "INCOMING"
  outgoing-direction: "OUTGOING"
  processes:
    - id: "PayeeQuoteTransfer"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transfer-type}"
    - id: "PayerTransactionRequest"
      direction: "${bpmn.incoming-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "PayerFundTransfer"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"
    - id: "PayeeTransactionRequest"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transaction-request-type}"
    - id: "transferProcess"
      direction: "UNKNOWN"
      type: "${bpmn.transfer-type}"
    - id: "international_remittance_payee_process"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"
    - id: "international_remittance_payer_process"
      direction: "${bpmn.outgoing-direction}"
      type: "${bpmn.transfer-type}"