datasource:
  core:
    host: alluvial-dev.cluster-crhg2ihxmnkn.eu-central-1.rds.amazonaws.com
    port: 5432
    schema: ph_ee_operations
    username: postgres
    password: password
  common:
    subprotocol: postgresql
    driverclass_name: org.postgresql.Driver
