kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"
    reset: false

spring:
  jpa:
    show-sql: false
    properties:
      eclipselink:
        logging:
          logger: "hu.dpc.phee.operator.config.EclipselinkLogger"
    open-in-view: false
  datasource:
    url: "jdbc:mysql://operator-mysql:3306/operator?rewriteBatchedStatements=true"
    username: "mifos"
    password: "password"

server:
  port: 8000
