apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-gsma"
  labels:
    app: ph-ee-connector-gsma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-gsma
  template:
    metadata:
      labels:
        app: ph-ee-connector-gsma
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-gsma-mm
          image: "{{ .Values.gsma.image }}"
          ports:
            - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.gsma.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
          resources:
            limits:
              memory: "400M"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-gsma
  name: ph-ee-connector-gsma
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-gsma
  sessionAffinity: None
  type: ClusterIP
