apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-mifos"
  labels:
    app: ph-ee-connector-ams-mifos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-ams-mifos
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-mifos
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-ams-mifos
          image: "{{ .Values.mifos_connector.image }}"
          ports:
            - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.mifos_connector.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
          resources:
            limits:
              memory: "400M"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
