apiVersion: apps/v1
kind: Deployment
metadata:
  name: "message-gateway"
  labels:
    app: message-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-gateway
  template:
    metadata:
      labels:
        app: message-gateway
    spec:
      containers:
        - name: message-gateway
          image: us.icr.io/phee-ns/message-gateway
          ports:
            - containerPort: 9191
          imagePullPolicy: Always
          env:
            - name: spring.datasource.url
              value: jdbc:mysql:thin://operations-mysql:3306/messagegateway
            - name: spring.datasource.username
              value: mifos
            - name: spring.datasource.password
              value: password
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

