apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-pesa"
  labels:
    app: ph-ee-connector-ams-pesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-ams-pesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-pesa
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-ams-pesa
          image: us.icr.io/phee-ns/phee-connector-ams-pesa
          ports:
            - containerPort: 5000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_pesa.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"