apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
  annotations:
spec:
  containers:
    - name: kafka
      image: spotify/kafka
      resources:
            limits:
              memory: "1536M"
      ports:
        - containerPort: 2181
        - containerPort: 9092
      env:
        - name: "ADVERTISED_HOST"
          value: "kafka"
        - name: "ADVERTISED_PORT"
          value: "9092"
  restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    nodePort: 30092
  type: NodePort

