apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-zeebe-ops"
  labels:
    app: ph-ee-zeebe-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-zeebe-ops
  template:
    metadata:
      labels:
        app: ph-ee-zeebe-ops
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-zeebe-ops
          image: "{{ .Values.zeebe_ops.image }}"
          ports:
            - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ph-ee-zeebe-ops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Values.zeebe_ops.hostname }}"
      http:
        paths:
        - backend:
            serviceName: ph-ee-zeebe-ops
            servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-zeebe-ops
  name: ph-ee-zeebe-ops
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-zeebe-ops
  sessionAffinity: None
  type: ClusterIP