apiVersion: v1
entries:
  ph-ee-engine:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-12-02T19:41:00.174499+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: b0e68101d33ae037dbdece6dae4f3ecd2c0c10ad56ba98a971a34c5079d93e40
    name: ph-ee-engine
    urls:
    - ph-ee-engine-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
generated: "2021-12-02T19:41:00.13056+05:30"
