apiVersion: v1
entries:
  ph-ee-engine:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-01-18T19:50:43.882328+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: cbc4f5adba3b90844834cfc14c5a61b959b4f3151bd9952bef1698015bf801e3
    name: ph-ee-engine
    urls:
    - ph-ee-engine-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
  ph-ee-engine-oaf:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-01-18T19:50:43.91132+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: 186218e4e82800564ace9db3037c8088a6cafc20ec3d8074934aebdb4c1df64c
    name: ph-ee-engine-oaf
    urls:
    - ph-ee-engine-oaf-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
generated: "2022-01-18T19:50:43.8485+05:30"
