apiVersion: v1
entries:
  ph-ee-engine:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-01-18T16:52:20.783348+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: 28e622d4aa2506d9de16569a55cbbf13377f1e0447a972c3fcee289ac808147e
    name: ph-ee-engine
    urls:
    - ph-ee-engine-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
  ph-ee-engine-oaf:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-01-18T16:52:20.848904+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: 265683f446cda5ec904721c38633e6dfe1b46b25b28833d19ea377ac8a7eb2c1
    name: ph-ee-engine-oaf
    urls:
    - ph-ee-engine-oaf-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
generated: "2022-01-18T16:52:20.703496+05:30"
