apiVersion: v1
entries:
  ph-ee-engine:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-12-02T02:17:51.035493+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: 42b5ba0d063653fe9c50be8e3c9f372d369f06fbc5993eab940b57e1165f8ece
    name: ph-ee-engine
    urls:
    - ph-ee-engine-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
generated: "2021-12-02T02:17:50.998116+05:30"
