apiVersion: v1
entries:
  ph-ee-engine:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-11-24T21:14:20.5795016+05:30"
    dependencies:
    - name: zeebe-cluster-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - condition: zeebe-operate.enabled
      name: zeebe-operate-helm
      repository: https://helm.camunda.io
      version: 1.0.0
    - name: elasticsearch
      repository: http://helm.elastic.co
      version: 7.13.2
    - condition: kibana.enabled
      name: kibana
      repository: http://helm.elastic.co
      version: 7.13.2
    - alias: operationsMysql
      condition: operations.enabled
      name: mysql
      repository: https://charts.helm.sh/stable
      version: 1.6.2
    description: PaymentHub EE Engine
    digest: a679da7f9c57b228d4e491ab7c4ae2740b72978279375dfbacc50746df18133d
    name: ph-ee-engine
    urls:
    - ph-ee-engine-1.0.0-SNAPSHOT.tgz
    version: 1.0.0-SNAPSHOT
generated: "2021-11-24T21:14:20.5490594+05:30"
