server:
  port: 9090

spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql:thin://localhost:3306/IdentityAccountMapper
    username: root
    password: mysql
    driver-class-name: org.drizzle.jdbc.DrizzleDriver

logging:
  level:
    ROOT: INFO

async:
  core-pool-size: 10
  max-pool-size: 10
  queue-capacity: 100