server:
  port: 8080

spring:
  jpa:
    show-sql: false
    generate-ddl: false

  datasource:
    url: jdbc:mysql:thin://operations-mysql:3306/IdentityAccountMapper
    username: root
    password: mysql
    driver-class-name: org.drizzle.jdbc.DrizzleDriver

logging:
  level:
    ROOT: DEBUG

async:
  core-pool-size: 10
  max-pool-size: 10
  queue-capacity: 100