apiVersion: v1
kind: Pod
metadata:
  name: "ph-ee-connector-channel"
  labels:
    app: ph-ee-connector-channel
  annotations:
spec:
  containers:
    - name: phee-connector-channel
      image: paymenthubee.azurecr.io/phee/connector-channel
      ports:
        - containerPort: 5000
      env: 
        - name: "zeebe.broker.contactpoint"
          value: "ph-ee-zeebe:26500"
  restartPolicy: Always

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ph-ee-connector-channel
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: ph-ee-connector-channel
      http:
        paths:
        - backend:
            serviceName: ph-ee-connector-channel
            servicePort: 80

