apiVersion: v1
kind: Pod
metadata:
  name: "ph-ee-connector-ams-mifos"
  labels:
    app: ph-ee-connector-ams-mifos
  annotations:
spec:
  containers:
    - name: phee-connector-ams-mifos
      image: paymenthubee.azurecr.io/phee/connector-ams-mifos
      ports:
        - containerPort: 5000
      env: 
        - name: "SPRING_PROFILES_ACTIVE"
          value: "{{ .Values.ph_ee_connector_ams_mifos.SPRING_PROFILES_ACTIVE }}"
  restartPolicy: Always

