{{- if .Values.mock_oracle.enabled -}}

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "mock-oracle"
  labels:
    app: mock-oracle
spec:
  replicas: {{ .Values.mock_oracle.replicas }}
  selector:
    matchLabels:
      app: mock-oracle
  template:
    metadata:
      labels:
        app: mock-oracle
      annotations:
{{- if .Values.mock_oracle.deployment.annotations }}
{{ toYaml .Values.mock_oracle.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: mock-oracle
          image: "{{ .Values.mock_oracle.image }}"
          imagePullPolicy: "{{ .Values.mock_oracle.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.mock_oracle.limits.memory }}"
              cpu: "{{ .Values.mock_oracle.limits.cpu }}"
            requests:
              memory: "{{ .Values.mock_oracle.requests.memory }}"
              cpu: "{{ .Values.mock_oracle.requests.cpu }}"
          ports:
            - containerPort: 4100
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: mock-oracle
  name: mock-oracle
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: {{ .Values.mock_oracle.service.targetport}}
  selector:
    app: mock-oracle
  sessionAffinity: None
  type: ClusterIP
---
{{- if .Values.mock_oracle.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: mock-oracle
  annotations:
{{- if .Values.mock_oracle.ingress.annotations }}
{{ toYaml .Values.mock_oracle.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.mock_oracle.hostname }}"
      http:
        paths:
        - path: "{{ .Values.mock_oracle.ingress.path }}"
          pathType: Prefix
          backend:
{{- if .Values.mock_oracle.ingress.backend }}
{{ toYaml .Values.mock_oracle.ingress.backend | indent 14 }}
{{- end }}

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end }}